apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic-bfu2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic-bfu2
    app.kubernetes.io/part-of: my-app
  name: devfile-sample-go-basic-bfu2
  namespace: cbanavik-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: devfile-sample-go-basic-bfu2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: devfile-sample-go-basic-bfu2
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:Oqe-2-devfile-sample-go-basic-bfu2
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
